"""empty message

Revision ID: 046506411cc7
Revises: 80eb0324433e
Create Date: 2023-01-24 16:35:36.014238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046506411cc7'
down_revision = '80eb0324433e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('author')
    # ### end Alembic commands ###
